config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "karjjq&erica&liti&dragic"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

  resources :posts, only: [:index, :show]
  resources :technotes, only: [:index, :show]
  resources :portfolios, only: [:index, :show]
  get "vitablogs/about", to:'vitablogs#about'

  namespace :author, path: "erica&rebecca&liti&vita" do
    resources :posts
    resources :technotes
    resources :portfolios
    root "posts#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  validates :title, :body, :description, :image, presence: true

  mount_uploader :image, PhotoUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, :body, :description, :image, presence: true

  mount_uploader :image, PhotoUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/technote.rb
class Technote < ApplicationRecord

  validates :title, :body, :description, :image, presence: true

  mount_uploader :image, PhotoUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/author/base_controller.rb
class Author::BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/author/portfolios_controller.rb
class Author::PortfoliosController < Author::BaseController

  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  def index
    @portfolios = Portfolio.all
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      flash[:notice] = "Portfolio 建立成功"
      redirect_to author_portfolios_path
    else
      flash[:alert] = "Portfolio 建立不成功"
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @portfolio.update(portfolio_params)
      flash[:notice] = "Portfolio 修改成功"
      redirect_to author_portfolios_path
    else
      flash[:alert] = "Portfolio 修改不成功"
      render "edit"
    end
  end

  def destroy
    @portfolio.destroy
    flash[:alert] = "Portfolio 刪除"
    redirect_to author_portfolios_path
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :body, :description, :image)
  end

  def set_portfolio
    @portfolio = Portfolio.friendly.find(params[:id])
  end

end

app/controllers/author/posts_controller.rb
class Author::PostsController < Author::BaseController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post 建立成功"
      redirect_to author_posts_path
    else
      flash[:alert] = "Post 建立不成功"
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post 修改成功"
      redirect_to author_posts_path
    else
      flash[:alert] = "Post 修改不成功"
      render "edit"
    end
  end

  def destroy
    @post.destroy
    flash[:alert] = "Post 刪除"
    redirect_to author_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :description, :image)
  end

  def set_post
    @post = Post.friendly.find(params[:id])
  end

end

app/controllers/author/technotes_controller.rb
class Author::TechnotesController < Author::BaseController

  before_action :set_technote, only: [:show, :edit, :update, :destroy]

  def index
    @technotes = Technote.order("created_at DESC")
  end

  def new
    @technote = Technote.new
  end

  def create
    @technote = Technote.new(technote_params)
    if @technote.save
      flash[:notice] = "TechNote 建立成功"
      redirect_to author_technotes_path
    else
      flash[:alert] = "TechNote 建立不成功"
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @technote.update(technote_params)
      flash[:notice] = "TechNote 修改成功"
      redirect_to author_technotes_path
    else
      flash[:notice] = "TechNote 修改不成功"
      render "edit"
    end
  end

  def destroy
    @technote.destroy
    flash[:alert] = "Post 刪除"
    redirect_to author_technotes_path
  end


  private

  def technote_params
    params.require(:technote).permit(:title, :body, :description, :image)
  end

  def set_technote
    @technote = Technote.friendly.find(params[:id])
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  def index
    @portfolios = Portfolio.order("created_at DESC")
  end

  def show
    @portfolio = Portfolio.friendly.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order("created_at DESC")
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

end

app/controllers/technotes_controller.rb
class TechnotesController < ApplicationController

  def index
    @technotes = Technote.order("created_at DESC")
  end

  def show
    @technote = Technote.friendly.find(params[:id])
  end

end

app/controllers/vitablogs_controller.rb
class VitablogsController < ApplicationController

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author/portfolios_helper.rb
module Author::PortfoliosHelper
end

app/helpers/author/posts_helper.rb
module Author::PostsHelper
end

app/helpers/author/technotes_helper.rb
module Author::TechnotesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/technotes_helper.rb
module TechnotesHelper
end

app/helpers/vitablogs_helper.rb
module VitablogsHelper
end

app/views/author/portfolios/_form.html.erb
<div class="container mt-4">
  <%= form_for [:author, @portfolio] do |f| %>

    <% if @portfolio.errors.any? %>
      <h2>We have some errors here !</h2>
      <ul>
        <% @portfolio.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body form-color">
            <% if @portfolio.new_record? %>
              <h5 class="card-title mb-0">New Post</h5>
            <% else %>
              <h5 class="card-title mb-0">
                <b>Edit</b>
                <span class="thin-text"><%= @portfolio.title %></span>
              </h5>
            <% end %>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="form-group mb-0">
                <% if @portfolio.image.blank? %>
                  <img src="http://via.placeholder.com/370x250", class= "img-thumbnail mb-1">
                <% else %>
                  <%= image_tag @portfolio.image, class: "img-thumbnail mb-1" %>
                <% end %>
              </div>
              <div class="custom-file">
                <%= f.label :image, "請選擇圖片", class: "custom-file-label" %>
                <%= f.file_field :image, class: "custom-file-input" %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="form-group mb-0">
                <%= f.label :title, "Title：" %>
                <%= f.text_field :title, class: "form-control form-color" %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="form-group mb-0">
                <%= f.label :description, "Description：" %>
                <%= f.text_area :description, class: "form-control form-color", rows: "5" %>
              </div>
            </li>
            <li class="list-group-item form-color">
              <div class="form-group mb-0">
                <%= f.submit class: "btn btn-success btn-block" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <div class="form-group">
          <%= f.text_area :body, class: "form-control" %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/author/portfolios/edit.html.erb
<%= tinymce_assets %>
<%= render "form" %>

app/views/author/portfolios/index.html.erb
<div class="container mt-4">
  <%= link_to "新增作品", new_author_portfolio_path, class: "btn btn-dark mb-2" %>

  <table class="table table-striped">
    <caption class="text-dark">List of PortFolios</caption>
    <thead class="thead-dark">
      <tr>
        <th scope="col">編號</th>
        <th scope="col">標題</th>
        <th scope="col">預覽</th>
        <th scope="col">編輯</th>
        <th scope="col">刪除</th>
      </tr>
    </thead>
    <tbody>
      <% @portfolios.each do |portfolio| %>
        <tr>
          <td><%= portfolio.id %></td>
          <td><%= portfolio.title %></td>
          <td>
            <%= link_to author_portfolio_path(portfolio) do %>
              <i class="fa fa-eye text-muted"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_author_portfolio_path(portfolio) do %>
              <i class="fas fa-pencil-alt text-muted"></i>
            <% end %>
          </td>
          <td>
            <%= link_to author_portfolio_path(portfolio),method: :delete, data: {confirm: "Are you sure?"} do %>
              <i class="fab fa-expeditedssl text-danger"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/author/portfolios/new.html.erb
<%= tinymce_assets %>
<%= render "form" %>

app/views/author/portfolios/show.html.erb
<div class="container mt-4">
  <div class="row">

    <div class="col-md-5">
      <%= image_tag @portfolio.image, class: "img-thumbnail" %>
      <p><%= simple_format @portfolio.description %></p>
    </div>

    <div class="col-md-7">
      <h2><%= @portfolio.title %></h2>
      <hr>
      <p class="lead"><%= @portfolio.body.html_safe %></p>
    </div>

  </div>
</div>

app/views/author/posts/_form.html.erb
<div class="container mt-4">
  <%= form_for [:author, @post] do |f| %>

    <% if @post.errors.any? %>
      <h2>We have some errors here !</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body form-color">
            <% if @post.new_record? %>
              <h5 class="card-title mb-0">New Post</h5>
            <% else %>
              <h5 class="card-title mb-0">
                <b>Edit</b>
                <span class="thin-text"><%= @post.title %></span>
              </h5>
            <% end %>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="form-group mb-0">
                <% if @post.image.blank? %>
                  <img src="http://via.placeholder.com/370x250", class= "img-thumbnail mb-1">
                <% else %>
                  <%= image_tag @post.image, class: "img-thumbnail mb-1" %>
                <% end %>
              </div>
              <div class="custom-file">
                <%= f.label :image, "請選擇圖片", class: "custom-file-label" %>
                <%= f.file_field :image, class: "custom-file-input" %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="form-group mb-0">
                <%= f.label :title, "Title：" %>
                <%= f.text_field :title, class: "form-control form-color" %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="form-group mb-0">
                <%= f.label :description, "Description：" %>
                <%= f.text_area :description, class: "form-control form-color", rows: "5" %>
              </div>
            </li>
            <li class="list-group-item form-color">
              <div class="form-group mb-0">
                <%= f.submit class: "btn btn-success btn-block" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <div class="form-group">
          <%= f.text_area :body, class: "form-control" %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/author/posts/index.html.erb
<div class="container">
  <%= link_to '新增日記', new_author_post_path, class: "btn btn-dark mb-2 mt-4" %>

  <table class="table table-striped">
    <caption class="text-dark">List of Posts</caption>
    <thead class="thead-dark">
      <tr>
        <th scope="col">編號</th>
        <th scope="col">標題</th>
        <th scope="col">預覽</th>
        <th scope="col">編輯</th>
        <th scope="col">刪除</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.id %></td>
          <td><%= post.title %></td>
          <td>
            <%= link_to author_post_path(post) do %>
              <i class="fa fa-eye text-muted"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_author_post_path(post) do %>
              <i class="fas fa-pencil-alt text-muted"></i>
            <% end %>
          </td>
          <td>
            <%= link_to author_post_path(post),method: :delete, data: {confirm: "Are you sure?"} do %>
              <i class="fab fa-expeditedssl text-danger"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/author/posts/show.html.erb
<div class="container mt-4">
  <div class="row">

    <div class="col-md-5">
      <%= image_tag @post.image, class: "img-thumbnail" %>
      <p><%= simple_format @post.description %></p>
    </div>

    <div class="col-md-7">
      <h2><%= @post.title %></h2>
      <hr>
      <p class="lead"><%= @post.body.html_safe %></p>
    </div>

  </div>
</div>

app/views/author/technotes/_form.html.erb
<div class="container mt-4">
  <%= form_for [:author, @technote] do |f| %>

    <% if @technote.errors.any? %>
      <h2>We have some errors here !</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body form-color">
            <% if @technote.new_record? %>
              <h5 class="card-title mb-0">New Post</h5>
            <% else %>
              <h5 class="card-title mb-0">
                <b>Edit</b>
                <span class="thin-text"><%= @technote.title %></span>
              </h5>
            <% end %>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="form-group mb-0">
                <% if @technote.image.blank? %>
                  <img src="http://via.placeholder.com/370x250", class= "img-thumbnail mb-1">
                <% else %>
                  <%= image_tag @technote.image, class: "img-thumbnail mb-1" %>
                <% end %>
              </div>
              <div class="custom-file">
                <%= f.label :image, "請選擇圖片", class: "custom-file-label" %>
                <%= f.file_field :image, class: "custom-file-input" %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="form-group mb-0">
                <%= f.label :title, "Title：" %>
                <%= f.text_field :title, class: "form-control form-color" %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="form-group mb-0">
                <%= f.label :description, "Description：" %>
                <%= f.text_area :description, class: "form-control form-color", rows: "5" %>
              </div>
            </li>
            <li class="list-group-item form-color">
              <div class="form-group mb-0">
                <%= f.submit class: "btn btn-success btn-block" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <div class="form-group">
          <%= f.text_area :body, class: "form-control" %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/author/technotes/index.html.erb
<div class="container">
  <%= link_to "新增程式分享", new_author_technote_path, class: "btn btn-dark mb-2 mt-4" %>

  <table class="table table-striped">
    <caption class="text-dark">List of TechNotes</caption>
    <thead class="thead-dark">
      <tr>
        <th scope="col">編號</th>
        <th scope="col">標題</th>
        <th scope="col">預覽</th>
        <th scope="col">編輯</th>
        <th scope="col">刪除</th>
      </tr>
    </thead>
    <tbody>
      <% @technotes.each do |technote| %>
        <tr>
          <td><%= technote.id %></td>
          <td><%= technote.title %></td>
          <td>
            <%= link_to author_technote_path(technote) do %>
              <i class="fa fa-eye text-muted"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_author_technote_path(technote) do %>
              <i class="fas fa-pencil-alt text-muted"></i>
            <% end %>
          </td>
          <td>
            <%= link_to author_technote_path(technote),method: :delete, data: {confirm: "Are you sure?"} do %>
              <i class="fab fa-expeditedssl text-danger"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/author/technotes/show.html.erb
<div class="container mt-4">
  <div class="row">

    <div class="col-md-5">
      <%= image_tag @technote.image, class: "img-thumbnail" %>
      <p><%= simple_format @technote.description %></p>
    </div>

    <div class="col-md-7">
      <h2><%= @technote.title %></h2>
      <hr>
      <p class="lead"><%= @technote.body.html_safe %></p>
    </div>

  </div>
</div>

app/views/portfolios/index.html.erb
<section id="section_portfolios">
  <div class="container">
    <div class="row">
      <% @portfolios.each do |portfolio| %>
        <div class="col-md-4 mt-4">
          <div class="card-deck mb-4">
            <%= link_to portfolio_path(portfolio), style: "text-decoration: none;" do %>
              <div class="card" style="height: 410px;">
                <%= image_tag portfolio.image, class: "card-img-top" %>
                <div class="card-body">
                  <h5 class="card-title text-dark"><%= portfolio.title %></h5>
                  <p class="card-text text-muted">
                    <%= truncate(portfolio.description, length: 80) %>
                  </p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"><%= time_ago_in_words(portfolio.created_at) %> ago</small>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/portfolios/show.html.erb
<article id="article_technotes">
  <div class="container mt-4">
    <div class="row">

      <div class="col-md-5">
        <%= image_tag @portfolio.image, class: "img-thumbnail" %>
        <p><%=  simple_format @portfolio.description %></p>
      </div>

      <div class="col-md-7">
        <h2><%= @portfolio.title %></h2>
        <hr>
        <p class="lead"><%= @portfolio.body.html_safe %></p>
      </div>

    </div>
  </div>
</article>

app/views/posts/index.html.erb
<section id="section_posts">
  <div class="container">
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-md-4 mt-4">
          <div class="card-deck">
            <%= link_to post_path(post), style: "text-decoration: none;" do %>
              <div class="card" style="height: 410px;">
                <%= image_tag post.image, class: "card-img-top" %>
                <div class="card-body">
                  <h5 class="card-title text-dark"><%= post.title %></h5>
                  <p class="card-text text-muted">
                    <%= truncate(post.description, length: 80) %>
                  </p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"><%= time_ago_in_words(post.created_at) %> ago</small>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<article id="article_posts">
  <div class="container mt-4">
    <div class="row">

      <div class="col-md-5">
        <%= image_tag @post.image, class: "img-thumbnail" %>
        <p><%=  simple_format @post.description %></p>
      </div>

      <div class="col-md-7">
        <h2><%= @post.title %></h2>
        <hr>
        <p class="lead"><%= @post.body.html_safe %></p>
      </div>

    </div>
  </div>
</article>

app/views/technotes/index.html.erb
<section id="section_technotes">
  <div class="container">
    <div class="row">
      <% @technotes.each do |technote| %>
        <div class="col-md-4 mt-4">
          <div class="card-deck mb-4">
            <%= link_to technote_path(technote), style: "text-decoration: none;" do %>
              <div class="card" style="height: 410px;">
                <%= image_tag technote.image, class: "card-img-top" %>
                <div class="card-body">
                  <h5 class="card-title text-dark"><%= technote.title %></h5>
                  <p class="card-text text-muted">
                    <%= truncate(technote.description, length: 80) %>
                  </p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"><%= time_ago_in_words(technote.created_at) %> ago</small>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/technotes/show.html.erb
<article class="article_technotes">
  <div class="container mt-4">
    <div class="row">

      <div class="col-md-5">
        <%= image_tag @technote.image, class: "img-thumbnail" %>
        <p><%=  simple_format @technote.description %></p>
      </div>

      <div class="col-md-7">
        <h2><%= @technote.title %></h2>
        <hr>
        <p class="lead"><%= @technote.body.html_safe %></p>
      </div>

    </div>
  </div>
</article>

app/views/vitablogs/about.html.erb
<header class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="overlay"></div>
    <h1 class="display-4 text-center">WELCOME TO Vita's Blog</h1>
  </div>
</header>

<section id="section_about">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <p class="text-center">ABOUT</p>
      </div>
      <div class="col-md-6">
        <p>
          在因緣際會之下接觸了Ruby，便覺得這個程式語言很有趣，而後又接觸了Rails 之後才發現，透過這兩者可以讓開發變得這麼有趣。就算是半路出家的我，也深深感受到開發的成就感及樂趣，我樂於學習及持續進步，希望有朝一日能成為同時精通前端設計和後端開發的工程師，因此正朝著全端開發的路上前進中。
        </p>
      </div>
      <div class="col-md-3 text-center">
        <a href="https://www.cakeresume.com/vitata710" target="_blank" class="text-white"><i class="fa fa-file"></i>Link Cake Resume</a>
      </div>
    </div>
  </div>
</section>

<section id="section_education">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <p class="text-center">EDUCATION</p>
      </div>
      <div class="col-md-6">
        <h6>健行科技大學</h6>
        <p>電子工程所</p>
      </div>
      <div class="col-md-3">
        <p>2007/09 - 2009/06</p>
      </div>
    </div>
    <hr>
  </div>
</section>

<section id="section_work">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <p class="text-center">WORK</p>
      </div>
      <div class="col-md-6">
        <h6>華聚產業共同標準推動基金會@經理</h6>
        <p>董事會：董事會、功能性委員會議程、議事錄資料彙整。</p>
        <h6 class="mt-4">兩岸企業家峰會@秘書</h6>
        <ul>
          <li>行政總務：辦公室總務、器材管理、各類備品訂購、郵局信件寄送。</li>
          <li>各項活動支援：參與協助全體性活動事務。</li>
          <li>會員聯絡：與會員們溝通協調各項事務推動。</li>
        </ul>
      </div>
      <div class="col-md-3">
        <p>2017 年 9 月 - 2018 年 4 月</p>
        <p class="mt-5">2014 年 2 月 - 2017 年 9 月</p>
      </div>
    </div>
  </div>
</section>

<!-- <section id="section_skills">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <p class="text-center">SKILLS</p>
      </div>
      <div class="col-md-9">
        <div class="row">
          <div class="col-md-4">
            <p>HTML / CSS</p>
            <div class="block">
              <div class="block1"></div>
              <p>70/100</p>
            </div>
          </div>
          <div class="col-md-4">
            <p>Bootstrap 4</p>
            <div class="block">
              <div class="block1"></div>
              <p>70/100</p>
            </div>
          </div>
          <div class="col-md-4">
            <p>JavaScript</p>
            <div class="block">
              <div class="block2"></div>
              <p>50/100</p>
            </div>
          </div>
          <div class="col-md-4">
            <p>JQuery</p>
            <div class="block">
              <div class="block2"></div>
              <p>50/100</p>
            </div>
          </div>
          <div class="col-md-4">
            <p>RWD</p>
            <div class="block">
              <div class="block2"></div>
              <p>50/100</p>
            </div>
          </div>
          <div class="col-md-4">
            <p>Ruby</p>
            <div class="block">
              <div class="block2"></div>
              <p>50/100</p>
            </div>
          </div>
          <div class="col-md-4">
            <p>Rails</p>
            <div class="block">
              <div class="block1"></div>
              <p>70/100</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> -->

<section id="section_contact">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <p class="text-center">CONTACT</p>
      </div>
      <div class="col-md-6">
        <h6>Email</h6>
        <p>vitata710@gmail.com</p>
        <h6 class="mt-4">Phone</h6>
        <p>0919-561-596</p>
      </div>
      <div class="col-md-3">
        <p>SOCIAL LINKS</p>
        <a href="https://github.com/showlovezz" target="_blank"><i class="fab fa-github-alt"></i></a>
        <a href="https://www.facebook.com/shela.hsieh" target="_blank"><i class="fab fa-facebook-square ml-3"></i></a>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p>&copy; 2018 By Vita Blog | All Rights Reserved.</p>
      </div>
    </div>
  </div>
</footer>