config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "karjjq&erica&liti&dragic"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

  resources :posts, only: [:index, :show]
  resources :technotes, only: [:index, :show]
  resources :portfolios, only: [:index, :show]
  get "vitablogs/about", to:'vitablogs#about'

  namespace :author, path: "erica&rebecca&liti&vita" do
    resources :posts
    resources :technotes
    resources :portfolios
    root "posts#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  validates :title, :body, :description, :image, presence: true

  mount_uploader :image, PhotoUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, :body, :description, :image, presence: true

  mount_uploader :image, PhotoUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/technote.rb
class Technote < ApplicationRecord

  validates :title, :body, :description, :image, presence: true

  mount_uploader :image, PhotoUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/author/base_controller.rb
class Author::BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/author/posts_controller.rb
class Author::PostsController < Author::BaseController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post 建立成功"
      redirect_to author_posts_path
    else
      flash[:alert] = "Post 建立不成功"
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post 修改成功"
      redirect_to author_posts_path
    else
      flash[:alert] = "Post 修改不成功"
      render "edit"
    end
  end

  def destroy
    @post.destroy
    flash[:alert] = "Post 刪除"
    redirect_to author_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :description, :image)
  end

  def set_post
    @post = Post.friendly.find(params[:id])
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  def index
    @portfolios = Portfolio.order("created_at DESC")
  end

  def show
    @portfolio = Portfolio.friendly.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order("created_at DESC")
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

end

app/controllers/technotes_controller.rb
class TechnotesController < ApplicationController

  def index
    @technotes = Technote.order("created_at DESC")
  end

  def show
    @technote = Technote.friendly.find(params[:id])
  end

end

app/controllers/vitablogs_controller.rb
class VitablogsController < ApplicationController

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author/portfolios_helper.rb
module Author::PortfoliosHelper
end

app/helpers/author/posts_helper.rb
module Author::PostsHelper
end

app/helpers/author/technotes_helper.rb
module Author::TechnotesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/technotes_helper.rb
module TechnotesHelper
end

app/helpers/vitablogs_helper.rb
module VitablogsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-md navbar-light">
  <div class="container">

    <a class="navbar-brand" href="/">
      <span class="text-warning">
        <i class="fa fa-home"></i>Vita's
      </span>blog
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">

        <li class="nav-item">
          <%= link_to "Blog", posts_path, class: "nav-link muted" %>
        </li>

        <li class="nav-item">
          <%= link_to "TechNote", technotes_path, class: "nav-link muted" %>
        </li>

        <li class="nav-item">
          <%= link_to "PortFolio", portfolios_path, class: "nav-link muted" %>
        </li>

        <li class="nav-item">
          <%= link_to "About Vita", vitablogs_about_path, class: "nav-link muted" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle muted" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Vita's Blog
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "My posts", author_posts_path, class: "dropdown-item" %>
              <%= link_to "My TechNote", author_technotes_path, class: "dropdown-item" %>
              <%= link_to "My PortFolio", author_portfolios_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
                <%= link_to "登出", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>

      </ul>
    </div>

  </div>
</nav>

<% if flash[:notice] %>
  <div class="container mt-2">
    <div class="row">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="container">
    <div class="row">
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShelaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_post_show.html.erb
<div class="row">

  <div class="col-md-5">
    <%= image_tag @post.image, class: "img-thumbnail" %>
  </div>

  <div class="col-md-7">
    <h2><%= @post.title %></h2>
    <hr>
    <p class="lead size"><%= @post.body %></p>
    <br>
    <p><%= @post.description %></p>
  </div>
  <div class="col-md-12 mt-5">
    <%= link_to 'Back to index', author_posts_path, class: "btn btn-warning float-right" %>
  </div>

</div>